{{- if and .Values.mariadb.enabled (not .Values.mariadb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensips.mariadbSecretName" . }}
  labels:
    {{- include "opensips.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
type: Opaque
stringData:
  {{ .Values.mariadb.auth.rootPasswordKey }}: {{ .Values.mariadb.auth.rootPassword | default (randAlphaNum 32) | quote }}
  {{ .Values.mariadb.auth.passwordKey }}: {{ .Values.mariadb.auth.password | default (randAlphaNum 32) | quote }}
{{- end }}
