{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensips.mariadbFullname" . }}
  labels:
    {{- include "opensips.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    {{- include "opensips.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
{{- end }}
