{{- if .Values.registration.enabled }}
{{- if not .Values.registration.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensips.fullname" . }}-registration
  labels:
    {{- include "opensips.labels" . | nindent 4 }}
    app.kubernetes.io/component: opensips
type: Opaque
stringData:
  {{ .Values.registration.passwordKey }}: "change-me"
  {{ .Values.registration.authUsernameKey }}: {{ .Values.registration.username | default "user" | quote }}
{{- end }}
{{- end }}
